export const products = [
    {
      id: 1,
      owner: "1st",
      sellerName: "Rohith",
      productName: "Smartphone X",
      originalPrice: 29999,
      description: "A high-end smartphone with excellent features.",
      location: "New Delhi, India",
      date: "25 March 2025",
      image: "https://media.istockphoto.com/id/1414801672/photo/cardboard-box-with-cosmetics-product-in-front-od-open-door-buying-online-and-delivery.jpg?s=612x612&w=0&k=20&c=SA9VCzp-QtpzlliX8dM_uoH8K20U1gHqYfsWP08aLl0=",
    },
    {
      id: 2,
      owner: "2nd",
      sellerName: "Paige",
      productName: "Wireless Earbuds",
      originalPrice: 4999,
      description: "Noise-canceling earbuds with long battery life.",
      location: "Mumbai, India",
      date: "22 March 2025",
      image: "https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?cs=srgb&dl=pexels-madebymath-90946.jpg&fm=jpg",
    },
    {
      id: 3,
      owner: "1st",
      sellerName: "Ravi",
      productName: "Gaming Laptop",
      originalPrice: 79999,
      description: "Powerful gaming laptop with RTX graphics.",
      location: "Bangalore, India",
      date: "20 March 2025",
      image: "https://img.freepik.com/free-photo/front-view-eco-friendly-cleaning-products-set-with-cotton-swabs-soap_23-2148818491.jpg",
    },
    {
      id: 4,
      owner: "2nd",
      sellerName: "Hari",
      productName: "Gaming Laptop",
      originalPrice: 79999,
      description: "Powerful gaming laptop with RTX graphics.",
      location: "Bangalore, India",
      date: "20 March 2025",
      image: "https://i.pcmag.com/imagery/roundups/01hiB08j7yaJGJmPl2YhRRH-59..v1713199550.jpg",
    },
    {
      id: 5,
      owner: "1st",
      sellerName: "Spider man",
      productName: "Gaming Laptop",
      originalPrice: 79999,
      description: "Powerful gaming laptop with RTX graphics.",
      location: "Bangalore, India",
      date: "20 March 2025",
      image: "https://img.freepik.com/free-photo/front-view-eco-friendly-cleaning-products-set-with-cotton-swabs-soap_23-2148818491.jpg",
    },
    {
      id: 6,
      owner: "3rd",
      sellerName: "Batman",
      productName: "Smartphone X",
      originalPrice: 29999,
      description: "A high-end smartphone with excellent features.",
      location: "New Delhi, India",
      date: "25 March 2025",
      image: "https://media.istockphoto.com/id/1414801672/photo/cardboard-box-with-cosmetics-product-in-front-od-open-door-buying-online-and-delivery.jpg?s=612x612&w=0&k=20&c=SA9VCzp-QtpzlliX8dM_uoH8K20U1gHqYfsWP08aLl0=",
    },
    {
      id: 7,
      owner: "1st",
      sellerName: "Rajesh",
      productName: "Smartphone X",
      originalPrice: 29999,
      description: "A high-end smartphone with excellent features.",
      location: "New Delhi, India",
      date: "25 March 2025",
      image: "https://cdn.bikedekho.com/processedimages/tvs/tvs-akula-310/source/tvs-akula-3106766463fbc870.jpg",
    },
    {
      id: 8,
      owner: "2nd",
      sellerName: "Ram",
      productName: "Smartphone X",
      originalPrice: 29999,
      description: "A high-end smartphone with excellent features.",
      location: "New Delhi, India",
      date: "25 March 2025",
      image: "https://img.gaadibazaar.in/uv-images/4567581/conversions/dce88f20-a291-498d-a15b-e04601a30aed-vdp.webp",
    },
    {
      id: 9,
      owner: "3rd",
      sellerName: "Naruto",
      productName: "Smartphone X",
      originalPrice: 29999,
      description: "A high-end smartphone with excellent features.",
      location: "New Delhi, India",
      date: "25 March 2025",
      image: "https://media.istockphoto.com/id/1414801672/photo/cardboard-box-with-cosmetics-product-in-front-od-open-door-buying-online-and-delivery.jpg?s=612x612&w=0&k=20&c=SA9VCzp-QtpzlliX8dM_uoH8K20U1gHqYfsWP08aLl0=",
    },
    {
      id: 10,
      owner: "2nd",
      sellerName: "Moana",
      productName: "Smartphone X",
      originalPrice: 29999,
      description: "A high-end smartphone with excellent features.",
      location: "New Delhi, India",
      date: "25 March 2025",
      image: "https://media.istockphoto.com/id/1414801672/photo/cardboard-box-with-cosmetics-product-in-front-od-open-door-buying-online-and-delivery.jpg?s=612x612&w=0&k=20&c=SA9VCzp-QtpzlliX8dM_uoH8K20U1gHqYfsWP08aLl0=",
    },
    {
      id: 11,
      owner: "1st",
      sellerName: "Shawn michaels",
      productName: "Smartphone X",
      originalPrice: 29999,
      description: "A high-end smartphone with excellent features.",
      location: "New Delhi, India",
      date: "25 March 2025",
      image: "https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?cs=srgb&dl=pexels-madebymath-90946.jpg&fm=jpg",
    },
    {
      id: 12,
      owner: "2nd",
      sellerName: "John Cena",
      productName: "Smartphone X",
      originalPrice: 29999,
      description: "A high-end smartphone with excellent features.",
      location: "New Delhi, India",
      date: "25 March 2025",
      image: "https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?cs=srgb&dl=pexels-madebymath-90946.jpg&fm=jpg",
    },
    {
      id: 13,
      owner: "1st",
      sellerName: "Karthick",
      productName: "Gaming Laptop",
      originalPrice: 79999,
      description: "Powerful gaming laptop with RTX graphics.",
      location: "Bangalore, India",
      date: "20 March 2025",
      image: "https://img.freepik.com/free-photo/front-view-eco-friendly-cleaning-products-set-with-cotton-swabs-soap_23-2148818491.jpg",
    },
  ];